# site settings
title: BAY Homegoods
subtitle: #by BRYuly
main_header: Welcome to BAY Homegoods
description: Where our goal is to bring home baked goods <br /> from our home to yours!
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Brad Yuly
email: hello@bayhomegoods.com
phone: (123) 456-7890
street_address: 1311 W Verbena Dr.
city: Meridian
state: Idaho
zip_code: 83642
country: United States of America


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/bayhomegoods
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/bay_homegoods
linkedin_url: 
pinterest_url: 
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
